name: Setup Python and run Test
description: Build and run tests

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.12"

runs:
  using: composite
  steps:
  - name: Setup Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}

  - name: Install poetry
    shell: bash
    run: |
      set -e -x -o pipefail
      pip install poetry

  - name: Install dependencies
    shell: bash
    run: |
      set -e -x -o pipefail
      poetry install

  - name: Test
    shell: bash
    run: |
      poetry run black connectivity_check tests --check --verbose --diff
      poetry run pytest
