name: Validation

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate
        uses: ./.github/actions/setup-and-run-tests

